@host = http://localhost:3000
@token = your_jwt_token_here

### Upload user avatar
POST {{host}}/users/avatar
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar-angelina.jpg"
Content-Type: image/jpeg

< ./markup/img/avatar-angelina.jpg
--WebAppBoundary--
